//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampollionGUI_Update.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChampollionGUI_Update.Properties.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Champollion GUI v2:
        ///
        ///This program provides a Graphical User Interface (GUI) to li1nx&apos;s &quot;Champollion a PEX to Papyrus decompiler&quot;.
        ///Link to the original Champollion tool: http://www.nexusmods.com/skyrim/mods/35307/
        ///
        ///This program is a significant upgrade and modernizations of the original &quot;Champollion Graphical User Interface&quot; which was originallymade by Arron Dominion. 
        ///Link to the original Champollion GUI tool: https://www.nexusmods.com/skyrim/mods/82367
        ///
        ///Compared to the old Champollion GUI, th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ THE README BEFORE YOU POST ABOUT AN ISSUE! YOUR QUESTION IS
        ///LIKELY ANSWERED THERE ALREADY!
        ///The README can be found by clicking the README button
        ///
        ///If you have trouble and need assistance, please comments on the mod
        ///page on Nexus or post a new issue on the GitHub page. You are welcome
        ///to contact me directly on Steam
        ///https://steamcommunity.com/id/w1ndStrik3_official/, but I would highly
        ///prefer if you would post your issue on Nexus or GitHub, because other
        ///people might have the same issue as you,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champollion Interface Help:
        ///
        ///This document gives an outline of the steps you need to take:
        ///
        ///1)  Select a folder where your .pex files are located.
        ///
        ///2)  Check Output Source in Different Location if you want the
        ///    .psc to go to a folder of your own choosing.
        ///    
        ///    NOTE: By default, the source files be placed in 
        ///    folder_with_pex_files/source.
        ///    
        ///    2a) Select a folder where your .psc files will be saved to.
        ///
        ///3)  Check Generate Assembly if you want a human-readable assembly file.
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string readme_instructions {
            get {
                return ResourceManager.GetString("readme_instructions", resourceCulture);
            }
        }
    }
}
